connect 'jdbc:derby://localhost:1527/Stock;create=true';

CREATE TABLE Denree
(
    id integer primary key GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
    nom varchar(255) not null,
	quantite integer not null,
    categorie varchar(255) not null
);

